/**
 * Fallback catalog data, shaped exactly like the shared Firestore schema
 * (src/types/firestore.ts). Used by src/lib/firestore/*.ts whenever the
 * live collection is empty or unreachable, so the storefront still renders
 * realistically during development and automatically switches to real data
 * once products are added via the admin panel.
 *
 * Product photos are real (non-placeholder-looking) stock photography from
 * loremflickr.com, locked to a fixed id per product so they stay stable
 * across reloads. These are demo-only — real products added via the admin
 * panel will carry their own photography in `images`.
 */
import type { Product, Category, Banner } from "@/types/firestore";

function daysAgo(days: number) {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000);
}

function img(keyword: string, lock: number) {
  return `https://loremflickr.com/400/400/${keyword}?lock=${lock}`;
}

export const mockCategories: Category[] = [
  { id: "grocery", name: "Grocery", icon: "🥦", color: "#0e3b5c", productCount: 16, isActive: true, sortOrder: 1 },
  { id: "stationery", name: "Stationery", icon: "📓", color: "#f5a623", productCount: 29, isActive: true, sortOrder: 2 },
];

export const mockProducts: Product[] = [
  // Grocery
  { id: "p1", name: "Premium Toor Dal", description: "High-quality unpolished toor dal, rich in protein.", categoryId: "grocery", categoryName: "Grocery", price: 185, discountPrice: 169, discountPercent: 9, images: [img("lentils", 1)], unit: "1 kg", stock: 80, isAvailable: true, isFeatured: true, isPopular: true, isFlashDeal: false, rating: 4.7, reviewCount: 156, tags: ["dal", "staples"], createdAt: daysAgo(90) },
  { id: "p2", name: "Fortune Sunflower Oil", description: "Refined sunflower oil, light and healthy for everyday cooking.", categoryId: "grocery", categoryName: "Grocery", price: 179, discountPrice: 159, discountPercent: 11, images: [img("cookingoil", 2)], unit: "1 L pouch", stock: 65, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: true, rating: 4.5, reviewCount: 201, tags: ["oil"], createdAt: daysAgo(100) },
  { id: "p3", name: "India Gate Basmati Rice", description: "Aromatic long-grain basmati rice.", categoryId: "grocery", categoryName: "Grocery", price: 699, discountPrice: 599, discountPercent: 14, images: [img("rice", 3)], unit: "5 kg", stock: 30, isAvailable: true, isFeatured: true, isPopular: true, isFlashDeal: false, rating: 4.8, reviewCount: 412, tags: ["rice", "staples"], createdAt: daysAgo(120) },
  { id: "p4", name: "Amul Butter", description: "Pasteurised table butter made from fresh cream.", categoryId: "grocery", categoryName: "Grocery", price: 58, discountPrice: 55, discountPercent: 5, images: [img("butter", 4)], unit: "100 g", stock: 80, isAvailable: true, isFeatured: false, isPopular: true, isFlashDeal: false, rating: 4.6, reviewCount: 445, tags: ["dairy"], createdAt: daysAgo(10) },
  { id: "p5", name: "Aashirvaad Whole Wheat Atta", description: "100% whole wheat flour for soft, fluffy rotis.", categoryId: "grocery", categoryName: "Grocery", price: 259, discountPrice: 229, discountPercent: 12, images: [img("flour", 5)], unit: "5 kg", stock: 45, isAvailable: true, isFeatured: true, isPopular: true, isFlashDeal: false, rating: 4.7, reviewCount: 298, tags: ["atta", "staples"], createdAt: daysAgo(55) },
  { id: "p6", name: "Tata Salt", description: "Iodised salt for healthy, everyday cooking.", categoryId: "grocery", categoryName: "Grocery", price: 28, discountPrice: 25, discountPercent: 11, images: [img("salt", 6)], unit: "1 kg", stock: 150, isAvailable: true, isFeatured: false, isPopular: true, isFlashDeal: false, rating: 4.8, reviewCount: 890, tags: ["salt"], createdAt: daysAgo(300) },
  { id: "p7", name: "Madhur Pure Sugar", description: "Sulphurless, hygienically processed sugar.", categoryId: "grocery", categoryName: "Grocery", price: 52, discountPrice: 48, discountPercent: 8, images: [img("sugar", 7)], unit: "1 kg", stock: 100, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.5, reviewCount: 132, tags: ["sugar"], createdAt: daysAgo(200) },
  { id: "p8", name: "Everest Red Chilli Powder", description: "Vibrant, flavourful red chilli powder.", categoryId: "grocery", categoryName: "Grocery", price: 62, discountPrice: 56, discountPercent: 10, images: [img("spices", 8)], unit: "200 g", stock: 90, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: true, rating: 4.6, reviewCount: 87, tags: ["spices"], createdAt: daysAgo(40) },
  { id: "p9", name: "Everest Turmeric Powder", description: "Pure, aromatic turmeric powder.", categoryId: "grocery", categoryName: "Grocery", price: 48, discountPrice: 44, discountPercent: 8, images: [img("turmeric", 9)], unit: "200 g", stock: 95, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.5, reviewCount: 76, tags: ["spices"], createdAt: daysAgo(140) },
  { id: "p10", name: "Premium Moong Dal", description: "Split yellow moong dal, easy to digest and nutritious.", categoryId: "grocery", categoryName: "Grocery", price: 145, discountPrice: 132, discountPercent: 9, images: [img("lentils", 10)], unit: "1 kg", stock: 70, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.6, reviewCount: 94, tags: ["dal"], createdAt: daysAgo(15) },
  { id: "p11", name: "Brooke Bond Red Label Tea", description: "Rich, strong blend of the finest tea leaves.", categoryId: "grocery", categoryName: "Grocery", price: 235, discountPrice: 215, discountPercent: 9, images: [img("tea", 11)], unit: "500 g", stock: 60, isAvailable: true, isFeatured: true, isPopular: true, isFlashDeal: false, rating: 4.7, reviewCount: 320, tags: ["tea"], createdAt: daysAgo(70) },
  { id: "p12", name: "Bru Instant Coffee Powder", description: "Rich filter coffee aroma, instant convenience.", categoryId: "grocery", categoryName: "Grocery", price: 175, discountPrice: 159, discountPercent: 9, images: [img("coffee", 12)], unit: "200 g", stock: 55, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.5, reviewCount: 168, tags: ["coffee"], createdAt: daysAgo(25) },
  { id: "p13", name: "Amul Pure Ghee", description: "Rich, aromatic pure cow ghee, made the traditional way.", categoryId: "grocery", categoryName: "Grocery", price: 299, discountPrice: 279, discountPercent: 7, images: [img("ghee", 13)], unit: "500 ml", stock: 40, isAvailable: true, isFeatured: true, isPopular: false, isFlashDeal: false, rating: 4.8, reviewCount: 210, tags: ["ghee", "dairy"], createdAt: daysAgo(8) },
  { id: "p14", name: "Thick Poha (Flattened Rice)", description: "Light, fluffy poha — perfect for a quick breakfast.", categoryId: "grocery", categoryName: "Grocery", price: 65, discountPrice: 59, discountPercent: 9, images: [img("rice", 14)], unit: "500 g", stock: 75, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.4, reviewCount: 58, tags: ["poha"], createdAt: daysAgo(180) },
  { id: "p15", name: "Bansi Rava (Semolina)", description: "Fine sooji, ideal for upma, halwa and more.", categoryId: "grocery", categoryName: "Grocery", price: 72, discountPrice: 65, discountPercent: 10, images: [img("flour", 15)], unit: "1 kg", stock: 60, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.3, reviewCount: 41, tags: ["rava"], createdAt: daysAgo(4) },
  { id: "p16", name: "Instant Dosa & Idli Batter Mix", description: "Ready-to-cook batter mix for soft idlis and crisp dosas.", categoryId: "grocery", categoryName: "Grocery", price: 89, discountPrice: 79, discountPercent: 11, images: [img("pancake", 16)], unit: "1 kg", stock: 35, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: true, rating: 4.5, reviewCount: 63, tags: ["batter"], createdAt: daysAgo(20) },

  // Stationery
  { id: "p17", name: "Classmate Notebook — Single Line, Pack of 6", description: "172-page single-line ruled notebooks, pack of 6, ideal for school and office use.", categoryId: "stationery", categoryName: "Stationery", price: 399, discountPrice: 349, discountPercent: 13, images: [img("notebook", 17)], unit: "6 x 172 pages", stock: 40, isAvailable: true, isFeatured: true, isPopular: true, isFlashDeal: false, rating: 4.6, reviewCount: 212, tags: ["notebook", "school"], createdAt: daysAgo(40) },
  { id: "p18", name: "Camlin Geometry Box Set", description: "Complete geometry set with compass, divider, protractor, and scale.", categoryId: "stationery", categoryName: "Stationery", price: 150, discountPrice: 129, discountPercent: 15, images: [img("geometry", 18)], unit: "1 set", stock: 60, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.4, reviewCount: 88, tags: ["geometry", "school"], createdAt: daysAgo(5) },
  { id: "p19", name: "Reynolds Gel Pen — Blue, Pack of 10", description: "Smooth-writing blue gel pens, pack of 10.", categoryId: "stationery", categoryName: "Stationery", price: 200, discountPrice: 150, discountPercent: 25, images: [img("pen", 19)], unit: "10 pcs", stock: 120, isAvailable: true, isFeatured: false, isPopular: true, isFlashDeal: true, rating: 4.5, reviewCount: 340, tags: ["pen"], createdAt: daysAgo(60) },
  { id: "p20", name: "JK Copier A4 Paper — 500 Sheets", description: "Smooth, bright A4 copier paper for office and school use.", categoryId: "stationery", categoryName: "Stationery", price: 329, discountPrice: 289, discountPercent: 12, images: [img("paper", 20)], unit: "1 ream", stock: 55, isAvailable: true, isFeatured: false, isPopular: true, isFlashDeal: false, rating: 4.6, reviewCount: 133, tags: ["paper", "office"], createdAt: daysAgo(30) },
  { id: "p21", name: "Doms Grip Pencils, Pack of 10", description: "Dark, smudge-free graphite pencils with a comfortable grip.", categoryId: "stationery", categoryName: "Stationery", price: 60, discountPrice: 52, discountPercent: 13, images: [img("pencil", 21)], unit: "10 pcs", stock: 140, isAvailable: true, isFeatured: false, isPopular: true, isFlashDeal: false, rating: 4.6, reviewCount: 176, tags: ["pencil"], createdAt: daysAgo(12) },
  { id: "p22", name: "Camlin Wax Crayons — 24 Shades", description: "Bright, smooth crayons for young artists.", categoryId: "stationery", categoryName: "Stationery", price: 90, discountPrice: 79, discountPercent: 12, images: [img("crayons", 22)], unit: "24 shades", stock: 65, isAvailable: true, isFeatured: true, isPopular: false, isFlashDeal: false, rating: 4.5, reviewCount: 64, tags: ["crayons"], createdAt: daysAgo(3) },
  { id: "p23", name: "Nataraj Eraser, Pack of 5", description: "Smooth, non-smudging soft erasers.", categoryId: "stationery", categoryName: "Stationery", price: 25, discountPrice: 22, discountPercent: 12, images: [img("eraser", 23)], unit: "5 pcs", stock: 200, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.3, reviewCount: 39, tags: ["eraser"], createdAt: daysAgo(220) },
  { id: "p24", name: "Kangaro Sharpener, Pack of 3", description: "Precision-blade sharpeners for clean points.", categoryId: "stationery", categoryName: "Stationery", price: 30, discountPrice: 27, discountPercent: 10, images: [img("sharpener", 24)], unit: "3 pcs", stock: 160, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.2, reviewCount: 28, tags: ["sharpener"], createdAt: daysAgo(160) },
  { id: "p25", name: "Fevicol Glue Stick, Pack of 3", description: "Clean, quick-drying glue sticks for school projects.", categoryId: "stationery", categoryName: "Stationery", price: 75, discountPrice: 65, discountPercent: 13, images: [img("glue", 25)], unit: "3 pcs", stock: 85, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: true, rating: 4.4, reviewCount: 52, tags: ["glue"], createdAt: daysAgo(18) },
  { id: "p26", name: "Camlin Scissors", description: "Sharp, safe stainless-steel scissors with soft grip handles.", categoryId: "stationery", categoryName: "Stationery", price: 45, discountPrice: 39, discountPercent: 13, images: [img("scissors", 26)], unit: "1 pc", stock: 70, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.3, reviewCount: 33, tags: ["scissors"], createdAt: daysAgo(95) },
  { id: "p27", name: "Sticky Notes Pad, Multicolor", description: "Vibrant sticky notes for reminders and to-do lists.", categoryId: "stationery", categoryName: "Stationery", price: 55, discountPrice: 49, discountPercent: 11, images: [img("stickynotes", 27)], unit: "1 pad", stock: 110, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.5, reviewCount: 47, tags: ["sticky notes", "office"], createdAt: daysAgo(6) },
  { id: "p28", name: "Kangaro Stapler with Pins", description: "Compact stapler with a box of staple pins included.", categoryId: "stationery", categoryName: "Stationery", price: 129, discountPrice: 112, discountPercent: 13, images: [img("stapler", 28)], unit: "1 set", stock: 50, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.3, reviewCount: 47, tags: ["stapler", "office"], createdAt: daysAgo(50) },
  { id: "p29", name: "L-Shape File Folder, Pack of 10", description: "Clear plastic L-shape folders to keep documents safe.", categoryId: "stationery", categoryName: "Stationery", price: 110, discountPrice: 95, discountPercent: 14, images: [img("folder", 29)], unit: "10 pcs", stock: 65, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.2, reviewCount: 24, tags: ["file", "office"], createdAt: daysAgo(2) },
  { id: "p65", name: "Camlin Scale (Ruler) — 15cm, Pack of 2", description: "Clear, unbreakable plastic scales with accurate cm/inch markings.", categoryId: "stationery", categoryName: "Stationery", price: 40, discountPrice: 35, discountPercent: 13, images: [img("ruler", 65)], unit: "2 pcs", stock: 130, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.4, reviewCount: 41, tags: ["scale", "geometry", "school"], createdAt: daysAgo(9) },
  { id: "p66", name: "Camlin Color Pencils — 12 Shades", description: "Smooth-laying, richly pigmented colour pencils for school and craft work.", categoryId: "stationery", categoryName: "Stationery", price: 95, discountPrice: 82, discountPercent: 14, images: [img("colorpencils", 66)], unit: "12 shades", stock: 100, isAvailable: true, isFeatured: false, isPopular: true, isFlashDeal: false, rating: 4.6, reviewCount: 118, tags: ["pencil", "color pencils", "school"], createdAt: daysAgo(6) },
  { id: "p67", name: "Camlin Protractor & Set Square Kit", description: "Precision protractor and set squares for measuring angles and drawing accurate areas and shapes.", categoryId: "stationery", categoryName: "Stationery", price: 65, discountPrice: 56, discountPercent: 14, images: [img("protractor", 67)], unit: "1 kit", stock: 75, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.3, reviewCount: 29, tags: ["protractor", "geometry", "school"], createdAt: daysAgo(1) },

  // More Pencils & Geometry
  { id: "p30", name: "Apsara Platinum Pencils, Pack of 10", description: "Extra-dark, smooth-writing HB pencils with natural wood body — trusted by students across India.", categoryId: "stationery", categoryName: "Stationery", price: 55, discountPrice: 48, discountPercent: 13, images: [img("pencil", 30)], unit: "10 pcs", stock: 180, isAvailable: true, isFeatured: false, isPopular: true, isFlashDeal: false, rating: 4.7, reviewCount: 231, tags: ["pencil", "school"], createdAt: daysAgo(22) },
  { id: "p31", name: "Nataraj Pencils HB, Pack of 20", description: "Classic HB graphite pencils — lightweight, consistent hardness, smooth on paper.", categoryId: "stationery", categoryName: "Stationery", price: 80, discountPrice: 70, discountPercent: 13, images: [img("pencil", 31)], unit: "20 pcs", stock: 150, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: true, rating: 4.4, reviewCount: 145, tags: ["pencil", "school"], createdAt: daysAgo(45) },
  { id: "p32", name: "Doms Art Pencil Set (2B, 4B, 6B, 8B)", description: "Professional-grade art pencils in 4 grades for shading, sketching and figure drawing.", categoryId: "stationery", categoryName: "Stationery", price: 130, discountPrice: 110, discountPercent: 15, images: [img("sketch", 32)], unit: "8 pcs", stock: 70, isAvailable: true, isFeatured: true, isPopular: true, isFlashDeal: false, rating: 4.8, reviewCount: 89, tags: ["pencil", "art", "sketch"], createdAt: daysAgo(7) },
  { id: "p33", name: "Maped Geometry Box — Premium Metal", description: "Heavy-duty metal geometry set with large compass, mini compass, divider, protractor and set squares. Ideal for boards and competitive exams.", categoryId: "stationery", categoryName: "Stationery", price: 280, discountPrice: 240, discountPercent: 14, images: [img("compass", 33)], unit: "1 set", stock: 45, isAvailable: true, isFeatured: true, isPopular: true, isFlashDeal: false, rating: 4.7, reviewCount: 112, tags: ["geometry", "compass", "school"], createdAt: daysAgo(11) },
  { id: "p34", name: "Camlin Big Compass with Pencil", description: "Large-radius drawing compass with built-in pencil holder — for circles up to 30 cm diameter.", categoryId: "stationery", categoryName: "Stationery", price: 95, discountPrice: 82, discountPercent: 14, images: [img("compass", 34)], unit: "1 pc", stock: 55, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.4, reviewCount: 43, tags: ["compass", "geometry"], createdAt: daysAgo(33) },
  { id: "p35", name: "30 cm Transparent Scale, Pack of 2", description: "Long 30 cm unbreakable transparent scale with both cm and inch markings — essential for drawing and geometry.", categoryId: "stationery", categoryName: "Stationery", price: 50, discountPrice: 44, discountPercent: 12, images: [img("ruler", 35)], unit: "2 pcs", stock: 120, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.5, reviewCount: 67, tags: ["scale", "ruler", "geometry"], createdAt: daysAgo(14) },
  { id: "p36", name: "Drawing Sheets A3, Pack of 20", description: "Thick, bright A3 drawing sheets for art class and school projects — 100 gsm for heavy colour work.", categoryId: "stationery", categoryName: "Stationery", price: 120, discountPrice: 105, discountPercent: 13, images: [img("drawing", 36)], unit: "20 sheets", stock: 85, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.3, reviewCount: 38, tags: ["drawing sheet", "art"], createdAt: daysAgo(50) },
  { id: "p37", name: "Camlin Sketch Pens — 24 Shades", description: "Vibrant fibre-tip sketch pens with long-lasting ink — great for posters, crafts and colouring books.", categoryId: "stationery", categoryName: "Stationery", price: 135, discountPrice: 119, discountPercent: 12, images: [img("markers", 37)], unit: "24 shades", stock: 75, isAvailable: true, isFeatured: false, isPopular: true, isFlashDeal: true, rating: 4.6, reviewCount: 97, tags: ["sketch pens", "art", "school"], createdAt: daysAgo(3) },
  { id: "p38", name: "Graph Notebook — 100 Pages", description: "1 mm grid graph paper notebook, perfect for maths, engineering drawing and science practicals.", categoryId: "stationery", categoryName: "Stationery", price: 70, discountPrice: 60, discountPercent: 14, images: [img("notebook", 38)], unit: "100 pages", stock: 60, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.4, reviewCount: 54, tags: ["graph", "notebook", "school"], createdAt: daysAgo(20) },
  { id: "p39", name: "Doms Zoom Pencil Kit with Accessories", description: "All-in-one pencil kit: 10 pencils, eraser, sharpener and scale in a zip pouch — the complete starter kit for school.", categoryId: "stationery", categoryName: "Stationery", price: 110, discountPrice: 95, discountPercent: 14, images: [img("pencilcase", 39)], unit: "1 kit", stock: 90, isAvailable: true, isFeatured: true, isPopular: true, isFlashDeal: false, rating: 4.7, reviewCount: 163, tags: ["pencil", "kit", "school"], createdAt: daysAgo(5) },
  { id: "p40", name: "Classmate Spiral Notebook — A5", description: "160-page spiral-bound A5 notebook with ruled pages — handy size for notes, journaling and exam prep.", categoryId: "stationery", categoryName: "Stationery", price: 85, discountPrice: 74, discountPercent: 13, images: [img("notebook", 40)], unit: "160 pages", stock: 100, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.5, reviewCount: 76, tags: ["notebook", "spiral"], createdAt: daysAgo(28) },
  { id: "p41", name: "Whiteboard Marker Set — 4 Colours", description: "Chisel-tip whiteboard markers in black, blue, red and green with a dry-erase eraser included.", categoryId: "stationery", categoryName: "Stationery", price: 155, discountPrice: 135, discountPercent: 13, images: [img("markers", 41)], unit: "4 pcs + eraser", stock: 55, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.4, reviewCount: 31, tags: ["marker", "whiteboard", "office"], createdAt: daysAgo(60) },
  { id: "p42", name: "Highlighter Set — 5 Colours", description: "Fluorescent chisel-tip highlighters in yellow, pink, green, orange and blue — perfect for notes and textbooks.", categoryId: "stationery", categoryName: "Stationery", price: 99, discountPrice: 85, discountPercent: 14, images: [img("highlighter", 42)], unit: "5 pcs", stock: 80, isAvailable: true, isFeatured: false, isPopular: false, isFlashDeal: false, rating: 4.5, reviewCount: 58, tags: ["highlighter", "pen", "school"], createdAt: daysAgo(16) },
];

export const mockBanners: Banner[] = [
  { id: "b1", imageUrl: "", title: "Fresh grocery, delivered today", subtitle: "Order before 6 PM for same-day delivery in Salem", linkType: "category", linkValue: "grocery", isActive: true, sortOrder: 1 },
  { id: "b2", imageUrl: "", title: "Back-to-school stationery sale", subtitle: "Up to 25% off notebooks, pens & geometry sets", linkType: "category", linkValue: "stationery", isActive: true, sortOrder: 2 },
  { id: "b3", imageUrl: "", title: "Flash deals, every day", subtitle: "Limited-time prices on grocery & stationery essentials", linkType: "route", linkValue: "/deals", isActive: true, sortOrder: 3 },
];

export const mockReviews = [
  { id: "r1", name: "Priya S.", location: "Salem", rating: 5, comment: "Ordered groceries and notebooks together — delivered same evening. Great packaging and fresh stock." },
  { id: "r2", name: "Arun K.", location: "Salem", rating: 5, comment: "Been buying stationery for my kids from Valmiki for a year now. Always genuine brands, fair prices." },
  { id: "r3", name: "Meena R.", location: "Puthiragoumdanpalayam", rating: 4, comment: "Loyalty points actually add up to real savings. Customer support on WhatsApp is quick too." },
  { id: "r4", name: "Suresh V.", location: "Salem", rating: 5, comment: "The flash deals on groceries are genuinely useful — saved a lot this month." },
];

export const mockFaqs = [
  { q: "What areas do you deliver to?", a: "We currently deliver across Salem and surrounding areas including Puthiragoumdanpalayam. Enter your pincode on the product or cart page to check availability." },
  { q: "Do you offer Cash on Delivery?", a: "Yes, COD is available on eligible orders along with UPI, cards, net banking, and wallets via Razorpay." },
  { q: "How do loyalty points work?", a: "You earn points on every order which can be redeemed against future purchases. Points and history are visible in your account dashboard." },
  { q: "Can I return a product?", a: "Yes, most items can be returned within 7 days if unopened and unused. Perishable groceries are covered under our freshness guarantee instead." },
  { q: "How can I track my order?", a: "Once your order ships, you'll get a tracking link via SMS/WhatsApp, and live status is always visible under My Orders." },
];
